# Generated by Django 5.2.4 on 2025-09-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority', 'due_date']},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'انجام نشده'), ('doing', 'درحال انجام'), ('done', 'انجام شده')], default='todo', max_length=10),
        ),
    ]
